#
server:
  port: 7500
#
logging:
  config: classpath:logback-spring.xml
#
spring:
  application:
    name: study-springcloud-consumer-feign
  main:
    web-application-type: servlet
    banner-mode: off
    #当bean同名时，是否允许覆盖注册
    allow-bean-definition-overriding: true
  profiles:
    active: @env@
#    active: @env@, feign
#    active: @env@, ribbon
#    active: @env@, feign, ribbon
    #（★）acos
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#（★）Eureka
eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #ip-address:
  client:
    service-url:
      defaultZone: @eureka.server.list@
    enabled: true
    register-with-eureka: true
    fetch-registry: true
