#
server:
  port: 7400
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-consumer-feign
  main:
    web-application-type: servlet
    banner-mode: 'off'
    #当bean同名时，是否允许覆盖注册
    allow-bean-definition-overriding: true
  profiles:
    active: feign
