#
spring:
  cloud:
    #开启重试机制
    loadbalancer:
      retry:
        enabled: true
#
feign:
  #（★）http客户端！！！
  httpclient:
    enabled: true
    connection-timeout: 2000
    #max-connections: 200
  okhttp:
    enabled: false
  #（★）服务客户端
  client:
    #是否使用文件配置
    default-to-properties: true
    #默认配置名称
    default-config: default
    #配置
    config:
      #（▲）默认配置
      default:
        #超时
        connectTimeout: 5000
        readTimeout: 5000
#        #拦截器
#        requestInterceptors:
#          - study.springcloud.consumer.feign.support.feign.interceptor.CustomRequestInterceptor
#        #重试
#        retryer: study.springcloud.consumer.feign.support.feign.retryer.CustomRetryer
#        #decode404:
#        #errorDecoder:
#        #decoder:
#        #encoder:
      #（▲）特殊配置
      study-springcloud-provider:
        connectTimeout: 5000
        readTimeout: 4000
#        requestInterceptors:
#          - study.springcloud.consumer.feign.support.feign.interceptor.MyRequestInterceptor
#        #retryer: study.springcloud.consumer.feign.support.feign.SimpleRetryer
#
