#
server:
  port: 7400
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-client-feign
  main:
    web-application-type: servlet
  cloud:
    loadbalancer:
      #开启重试机制
      retry:
        enabled: false
#Eureka Client
eureka:
  instance:
    hostname: study-springcloud-client-feign
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: @eureka.instance.defaultZone@
#########################
#（★）Feign
#########################

feign:
  #（▲）客户端配置
  client:
    default-config: default
    default-to-properties: true
    config:
      default:
      - connectTimeout: 5000
      - readTimeout: 5000
  #（▲）压缩配置
  compression:
    request:
      enabled: true
      mime-types: text/xml, application/xml, application/json
      min-request-size: 2048
    response:
      enabled: true
  #（▲）HttpClient配置
  httpclient:
    enabled: true
    connection-timeout: 2000
    max-connections: 200
  #（▲）OKHttp配置
  okhttp:
    enabled: false
  #（）
  study-springcloud-provider:
    connectTimeout: 5000
    readTimeout: 5000
    retryer:

