#
server:
  port: 7400
#
logging:
  config: classpath:logback-spring.xml
#
spring:
  application:
    name: study-springcloud-consumer-feign
  main:
    web-application-type: servlet
    banner-mode: 'off'
    #当bean同名时，是否允许覆盖注册
    allow-bean-definition-overriding: true
  profiles:
    active: feign, @env@
#
eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: @eureka.server.list@
    register-with-eureka: true
    fetch-registry: true