#
spring:
  cloud:
    #开启重试机制
    loadbalancer:
      retry:
        enabled: false
    #服务注册和发现，Nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#
feign:
  #（▲）压缩配置
  compression:
    request:
      enabled: true
      mime-types: text/xml, application/xml, application/json
      min-request-size: 2048
    response:
      enabled: true
  #（▲）HttpClient配置
  httpclient:
    enabled: true
    #connection-timeout: 2000
    #max-connections: 200
  #（▲）OkHttp配置
  okhttp:
    enabled: false
  #（▲）客户端配置
#  client:
#    #默认配置名称
#    default-config: default
#    #文件配置是否覆盖代码配置
#    default-to-properties: true
#    config:
#      default:
#        connectTimeout: 8000
#        readTimeout: 6000
#        requestInterceptors: CustomRequestInterceptor
#        #retryer:
#        #errorDecoder:
#        #decoder:
#        #encoder:
#      #Client配置
#      study-springcloud-provider:
#        connectTimeout: 8000
#        readTimeout: 6000
