#
spring:
  cloud:
    #开启重试机制
    loadbalancer:
      retry:
        enabled: true
#
feign:
  #（★）http客户端！！！
  httpclient:
    enabled: false
    connection-timeout: 2000
    #max-connections: 200
  okhttp:
    enabled: true
  #（★）服务
  client:
    #是否使用文件配置
    default-to-properties: true
    #默认配置名称
    default-config: default
    #配置
    config:
      #（▲）默认
      default:
        #超时
        connectTimeout: 5000
        readTimeout: 5000
        #拦截器
        requestInterceptors:
          - CustomRequestInterceptor
#        #重试
#        retryer: CustomRetryer
#        #decode404:
#        #errorDecoder:
#        #decoder:
#        #encoder:
      #（▲）特殊
      study-springcloud-provider:
        connectTimeout: 5000
        readTimeout: 4000
        requestInterceptors:
          - MyRequestInterceptor
#        #retryer: study.springcloud.consumer.feign.support.feign.SimpleRetryer
#
